---
- name: ensure firewalld is installed
  package:
    name: firewalld
    state: present
  tags:
    - firewalld

- name: ensure firewalld is enabled and started
  service: 
    name: firewalld
    enabled: "{{ firewalld_enabled }}"
    state: "{{ firewalld_state }}"
  tags:
    - firewalld
    - firewalld.service

- name: include firewalld setup tasks
  include_tasks: firewalld.yml
  when: firewalld_state != "stopped"
  tags:
    - firewalld
